### PR TITLE
Adds dll_name kwarg to SDProcess's __init__ to enable passing of a DL…

### LINKED ISSUE #5: Pass dll_name As Arg To SDProcess
Update pysdtoken to enable the option of passing a dll path to SDProcess.

If not passed, load defaults for platform.

### PR DESCRIPTION
**Pull request by ssmithTaylor**
resolves: #5

### CODE REVIEW

**Comment by ssmithTaylor** [comment]
@XanaDublaKublaConch,

How do you want to handle collaboration with merges to master? Would you prefer to review/approve them yourself?

**Comment by XanaDublaKublaConch** [comment]
I don't think it's necessary right now. We have a common goal and you seem to have more experience on making things pythonic, so if any of your changes breaks the windows functionality, I'll just fix that part after your push. My next focus will be on multiple tokens support, which I don't actually need, but now I know it's broken so I feel compelled to fix it.

**Comment by ssmithTaylor** [comment]
Sounds good, I'll do my best to test on Windows as well (Though without a token I am somewhat limited).

For transparency's sake I think I'll start working in gitflow-like branches and then merge to master from there.

**Comment by XanaDublaKublaConch** [comment]
FYI - Common path on Windows is "C:\Program Files (x86)\RSA SecurID Token Common", but windll is always able to find it just by name in my experience on 3 different boxes, so I'm not sure a full path is necessary.

Also, I can put something on the wiki page about how to generate fake tokens using stoken.

**Comment by ssmithTaylor** [comment]
I could add a test to see if it loads without one (or just catch the exception). If it usually picks it up without a path it's probably better to not set one, then just have the fallback for if it fails without one.

Edit: Given there's a x86 and x64 version, it's probably better to just leave it as is for windows for now. If someone raises an issue for it we can look at a solution then.

For future me (or someone else), raised error type should be OSError. Error number 22, strerror = "The specified module could not be found".

**Pull request merged**
